version: '3'

services:
  api-staging:
    kind: Deployment
    image: __CONTAINER_IMAGE__
    environment:
      NODE_ENV: staging
      REDIS_HOST: redis
      REDIS_PORT: 6379
      POSTGRES_URI: 'postgres://bfast-admin:Ro0tie-Toot1e%21@postgres-staging.bfast-vn.net/plan-de-transport'
      POSTGRES_HOST: postgres-staging.bfast-vn.net
      POSTGRES_PORT: 5432
      POSTGRES_USER: bfast-admin
      POSTGRES_DATABASE:  plan-de-transport
      POSTGRES_PASSWORD: Ro0tie-Toot1e!
    deploy:
      placement:
        constraints:
          - node.hostname == prod1
      labels:
        - 'traefik.frontend.rule=Host:api.transport.staging.bfast-vn.net'
        - 'traefik.port=3000'
        - 'traefik.cluster-issuer=letsencrypt-prod'
    volumes:
      - storage-staging:/home/node/app/uploads
    imagePullSecrets: regcred
    imagePullPolicy: Always
    Ingress:
      default:
        metadata:
          annotations:
            nginx.ingress.kubernetes.io/ssl-passthrough: "true"
            nginx.ingress.kubernetes.io/proxy-body-size: 50m
            nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
            nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
            nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
  redis:
    image: redis:6
    expose:
      - 6379:6379
volumes:
  storage-staging:
    storage: 1Gi
